site_url: https://what-to-watch-sheepduck.netlify.app/
logo_url: https://amsterdamduckstore.com/wp-content/uploads/2019/12/Black-Sheep-Rubber-Duck-front-Amsterdam-Duck-Store.jpg

publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: master
  squash_merges: true

# used together with `npx netlify-cms-proxy-server`. https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
local_backend: true

media_folder: static/img
public_folder: /img

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - label: 'Site settings'
    name: 'site'
    files:
      - label: 'Info'
        name: 'info'
        file: 'content/site/info.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: Site Name, name: sitename, widget: string, hint: 'This is used for the site title' }
          - {
              label: Site Description,
              name: sitedescription,
              widget: string,
              hint: 'This is used as descriptive text for links that link to this site',
            }
          - {
              label: Site Language,
              name: sitelang,
              widget: string,
              pattern: ['^[a-z]{2}([-])?([A-Za-z]{2})?$', 'Must match "xx" or "xx-XX" syntax (ex. "en" or "sv-SE")'],
            }
          # - { label: Site Email, name: siteemail, widget: string, required: false }
  - name: 'series'
    label: 'Series'
    label_singular: 'Serie'
    folder: 'content/series'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    preview_path: '/{{slug}}'
    fields:
      - {
          label: 'Series kind',
          name: 'kind',
          widget: 'select',
          default: 'serie',
          options:
            [
              { label: 'Movie', value: 'movie' },
              { label: 'Serie', value: 'serie' },
              { label: 'Anime', value: 'anime' },
            ],
        }
      - {
          label: 'Series categorie',
          name: 'category',
          widget: 'select',
          default: 'action',
          options:
            [
              { label: 'Action', value: 'action' },
              { label: 'Horror', value: 'horror' },
              { label: 'Romance', value: 'romance' },
              { label: 'Drama', value: 'drama' },
              { label: 'Comedy', value: 'comdey' },
              { label: 'Crime', value: 'crime' },
              { label: 'Science-Fiction', value: 'science-fiction' },
            ],
        }
      - {
          label: 'Series Subcategorie',
          name: 'sub_category',
          widget: 'select',
          default: 'animals',
          options:
            [
              { label: 'Action', value: 'action' },
              { label: 'Horror', value: 'horror' },
              { label: 'Romance', value: 'romance' },
              { label: 'Drama', value: 'drama' },
              { label: 'Comedy', value: 'comdey' },
              { label: 'Crime', value: 'crime' },
              { label: 'Science-Fiction', value: 'science-fiction' },
            ],
        }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'IMDB ID', name: 'id', widget: 'string', required: true }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Cover Image', name: 'cover', widget: 'image', required: false, allow_multiple: false }
      - {
          label: 'Seen By',
          name: 'seen_by',
          widget: 'list',
          required: true,
          summary: '{{fields.person}}',
          field: { label: 'Person', name: 'person', widget: 'string' },
        }
